### ISSUE TITLE
주식가격 코드 올려주세여 ㅎ

### ISSUE THREAD

**Issue by miz2121** [simplealgostudy/AlgorithmStudy#17]
[프로그래머스/주식가격](https://programmers.co.kr/learn/courses/30/lessons/42584) 
여기서 작성한 코드를 올려주시면 됩니다. ㅎ

**Comment by sungmen** [comment]
파일은 [여기에](https://github.com/simplealgostudy/AlgorithmStudy/tree/master/200611)올리시면 됩니다.
